"""
Export Service - Generate downloadable exports (PPTX, PDF, Word)
"""
import os
import io
import json
from typing import Optional, List
from pydantic import BaseModel

# ============================================================================
# Models
# ============================================================================

class Slide(BaseModel):
    title: str
    content: Optional[str] = None
    bullet_points: Optional[List[str]] = None
    speaker_notes: Optional[str] = None
    layout: Optional[str] = "title_content"
    image_url: Optional[str] = None

class ExportSlidesRequest(BaseModel):
    slides: List[Slide]
    title: str
    format: str = "pptx"  # pptx, pdf, html
    template: Optional[str] = None

class ExportWordRequest(BaseModel):
    title: str
    sections: List[dict]
    include_toc: bool = True

# ============================================================================
# PowerPoint Export
# ============================================================================

async def export_slides_pptx(request: ExportSlidesRequest) -> bytes:
    """Generate a PowerPoint presentation"""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RgbColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        raise ValueError("python-pptx not installed. Run: pip install python-pptx")
    
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    
    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    title.text = request.title
    
    # Content slides
    content_layout = prs.slide_layouts[1]  # Title and content
    
    for slide_data in request.slides:
        slide = prs.slides.add_slide(content_layout)
        
        # Title
        if slide.shapes.title:
            slide.shapes.title.text = slide_data.title
        
        # Content
        if len(slide.placeholders) > 1:
            body = slide.placeholders[1]
            tf = body.text_frame
            
            if slide_data.bullet_points:
                for i, point in enumerate(slide_data.bullet_points):
                    if i == 0:
                        tf.text = point
                    else:
                        p = tf.add_paragraph()
                        p.text = point
                        p.level = 0
            elif slide_data.content:
                tf.text = slide_data.content
        
        # Speaker notes
        if slide_data.speaker_notes:
            notes_slide = slide.notes_slide
            notes_slide.notes_text_frame.text = slide_data.speaker_notes
    
    # Save to bytes
    output = io.BytesIO()
    prs.save(output)
    output.seek(0)
    return output.read()

# ============================================================================
# Word Export
# ============================================================================

async def export_word(request: ExportWordRequest) -> bytes:
    """Generate a Word document"""
    try:
        from docx import Document
        from docx.shared import Inches, Pt
    except ImportError:
        raise ValueError("python-docx not installed. Run: pip install python-docx")
    
    doc = Document()
    
    # Title
    doc.add_heading(request.title, 0)
    
    # Table of contents placeholder
    if request.include_toc:
        doc.add_paragraph("Table of Contents", style='Heading 1')
        doc.add_paragraph("[Table of contents will be generated by Word]")
        doc.add_page_break()
    
    # Sections
    for section in request.sections:
        doc.add_heading(section.get('title', 'Section'), level=1)
        
        if section.get('content'):
            doc.add_paragraph(section['content'])
        
        if section.get('subsections'):
            for sub in section['subsections']:
                doc.add_heading(sub.get('title', 'Subsection'), level=2)
                if sub.get('content'):
                    doc.add_paragraph(sub['content'])
    
    # Save to bytes
    output = io.BytesIO()
    doc.save(output)
    output.seek(0)
    return output.read()

# ============================================================================
# HTML Export (for PDF conversion)
# ============================================================================

async def export_slides_html(request: ExportSlidesRequest) -> str:
    """Generate HTML representation of slides"""
    html_parts = [f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{request.title}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 20px; }}
        .slide {{ 
            page-break-after: always; 
            border: 1px solid #ddd; 
            padding: 40px; 
            margin-bottom: 20px;
            min-height: 500px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 8px;
        }}
        .slide h1 {{ font-size: 2.5em; margin-bottom: 30px; }}
        .slide ul {{ font-size: 1.3em; line-height: 1.8; }}
        .slide p {{ font-size: 1.2em; line-height: 1.6; }}
        .notes {{ 
            background: #f5f5f5; 
            padding: 15px; 
            margin-top: 20px; 
            border-left: 4px solid #667eea;
            color: #333;
            border-radius: 4px;
        }}
    </style>
</head>
<body>
    <div class="slide">
        <h1>{request.title}</h1>
    </div>
"""]
    
    for slide in request.slides:
        html_parts.append(f'<div class="slide">')
        html_parts.append(f'<h1>{slide.title}</h1>')
        
        if slide.bullet_points:
            html_parts.append('<ul>')
            for point in slide.bullet_points:
                html_parts.append(f'<li>{point}</li>')
            html_parts.append('</ul>')
        elif slide.content:
            html_parts.append(f'<p>{slide.content}</p>')
        
        if slide.speaker_notes:
            html_parts.append(f'<div class="notes"><strong>Speaker Notes:</strong> {slide.speaker_notes}</div>')
        
        html_parts.append('</div>')
    
    html_parts.append('</body></html>')
    return '\n'.join(html_parts)
